### ISSUE TITLE
Design database tables

### ISSUE THREAD

**Issue by jslemmer** [Gang944/2020-GPW-L5K2-D#1]

**Comment by Gang944** [comment]
![908H OWVSF `7I$S801}~DP](https://user-images.githubusercontent.com/45256846/79707640-c8731000-82ef-11ea-8caa-c3775a780a28.png)

**Comment by Gang944** [comment]
![ERD](https://user-images.githubusercontent.com/45256846/79707723-fc4e3580-82ef-11ea-8fe1-0be8ebe0e549.png)
I finish most of the ERD, I have some questions about ordering food table. So there is no order form in ERD.

**Comment by Asunamm** [comment]
I think there is still need a table about administrator and staff

**Comment by IGPD** [comment]
I think the data should be expressed in different graphs, and the tables are too single.

**Comment by Asunamm** [comment]
![I(RRDIIWJS65T3FVACDC2SJ](https://user-images.githubusercontent.com/30548019/79709957-1f7be380-82f6-11ea-9918-dc66ddc58a14.png)

**Comment by Gang944** [comment]
> I think the data should be expressed in different graphs, and the tables are too single.

Good idea. Which graphs do you think is a nice choose for our project?

**Comment by IGPD** [comment]
> I think the data should be expressed in different graphs, and the tables are too single.
> 
> Good idea. Which graphs do you think is a nice choose for our project?
According to the way of data expression to decide the choice of graphics, such as rectangle to express differences.

**Comment by Wanghaoyi123** [comment]
The relation between the tables is too single, we can find more relation in the design.

**Comment by Asunamm** [comment]
@jslemmer  for example, the picture as a database table. So, if I just wanna show the NAME xxx on the website, other data is not needed, how can I code? when I code "SELECT name FROM the customer" in php file, how can I code to show the xxx in somewhere with the html code like<div></div>.
![H`XK((FLB5XIL1@AJC1RXK](https://user-images.githubusercontent.com/30548019/79728601-c70e0b80-8320-11ea-8364-666a73167120.png)

**Comment by jslemmer** [comment]
echo $row[name] ?

I do not really understand your question

**Comment by Asunamm** [comment]
@jslemmer  emmmm, echo $row[name] it give all the customer name, I just want the name of customer only one, on the customer name list.

**Comment by jslemmer** [comment]
WHERE ID = 1 ?

If you want to make a selection, you need a WHERE clause

**Comment by IGPD** [comment]
[Database (1).zip](https://github.com/Gang944/2020-GPW-L5K2-D/files/4513744/Database.1.zip)

**Comment by jslemmer** [comment]
What is the point of just throwing a file here without any additional comment or text?

**Comment by IGPD** [comment]
> Database (1).zip

This is the database, based on ERD.

**Comment by jslemmer** [comment]
Then explain that to your group members and ask them if there is any suggestion or if they have feedback?

**Comment by IGPD** [comment]
> Then explain that to your group members and ask them if there is any suggestion or if they have feedback?

Yes

**Comment by jslemmer** [comment]
Do there here in this issue, not somewhere else

**Comment by Asunamm** [comment]
Still not found the chart on week20. Can teacher send us the code by email on student website？

**Comment by Wanghaoyi123** [comment]
> ![ERD](https://user-images.githubusercontent.com/45256846/79707723-fc4e3580-82ef-11ea-8fe1-0be8ebe0e549.png)
> 我完成了旅客的ERD，对点餐表有一些疑问。因此，ERD中没有订单。

**Comment by Wanghaoyi123** [comment]
> ![ERD](https://user-images.githubusercontent.com/45256846/79707723-fc4e3580-82ef-11ea-8fe1-0be8ebe0e549.png)
> I finished the ERD of the traveler, I have some questions about ordering food table. So there is no order form in ERD.
We should add the table for ordering food, which I will add later.

**Comment by Wanghaoyi123** [comment]
> ![ERD](https://user-images.githubusercontent.com/45256846/79707723-fc4e3580-82ef-11ea-8fe1-0be8ebe0e549.png)
> I finished the ERD of the traveler, I have some questions about ordering food table. So there is no order form in ERD.

>We should add the table for ordering food, which I will add later.

**Comment by Wanghaoyi123** [comment]
![food order](https://user-images.githubusercontent.com/45254018/83349446-94b3ed00-a367-11ea-9c2e-0e11d16c2820.png)
This is the ERD for ordering food

**Comment by Wanghaoyi123** [comment]
![${77CVMR4RJ%QUFF3IBB@NH](https://user-images.githubusercontent.com/45254018/83349484-c9c03f80-a367-11ea-89b1-f141685c2df9.png)
This is the Table in the database about ordering food

**Comment by jslemmer** [comment]
You have not asked me an actual question. But there is not relationship between user and food table. Where is the relationship?

Just because you draw a line does not mean you have created a relationships. And what kind of relationship should this be?

**Comment by Wanghaoyi123** [comment]
The relationship between customer and food time should be one to many.  I will re-upload the relationship picture after the change
